#!/usr/bin/bash
echo y | sudo pacman -Syu chromium dmenu fish flameshot i3-wm i3blocks i3lock i3status libreoffice-still libreoffice-still-ru mesa-utils nitrogen picom rkhunter sqlitebrowser telegram-desktop timeshift vim yay mpv feh mupdf
