#!/usr/bin/python3
import os, subprocess

def run_command(command:str):
    print(f'RUN: {command}')
    subprocess.run(command, shell=True)

def i3_config():
    mkdir_i3 = "mkdir -p ~/.config/i3"
    mkdir_i3status = "mkdir -p ~/.config/i3status"
    
    run_command(command=mkdir_i3)
    run_command(command=mkdir_i3status)

def updateSystem():
    update = (
            "echo y | sudo pacman -Syu "
            "fish vim git chromium dmenu i3-wm i3status "
            "ibreoffice-still libreoffice-still-ru ranger"
            )
    run_command(command=update)

def settingsConfig():
    git_clone_config = "cd ~ && git clone https://github.com/rickert156/my_config"
    
    cp_i3 = "cp ~/my_config/i3/config ~/.config/i3/config"
    cp_i3status = "cp ~/my_config/i3status/config ~/.config/i3status/config"

    run_command(command=git_clone_config)
    run_command(command=co_i3)
    run_command(command=cp_i3status)


def createParserDir():
    mkdir_parser = "mkdir -p ~/Parser"
    run_command(command=mkdir_parser)


def InitMachine():
    updateSystem()

    i3_config()
    settingsConfig()
    createParserDir()


InitMachine()

